import { Header } from '@/ui/header';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="font-mono bg-slate-950 text-slate-100">
                <Header />
                <main className="pt-24 min-h-screen">{children}</main>
            </body>
        </html>
    );
}
